FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as builder

WORKDIR /app

EXPOSE 5000

RUN dotnet restore

RUN mkdir temp && chmod 777 -R temp
COPY . temp/
RUN cd temp/ && dotnet restore && dotnet build && dotnet test
RUN cd temp/ && mkdir dist && chmod 777 -R dist/
RUN cd temp/ && dotnet publish -o dist/

# Runtime image creation
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

# Uncomment the line below if running with HTTPS
# ENV ASPNETCORE_URLS=https://+:443

WORKDIR /app
COPY --from=build /app/temp/dist ./

ENTRYPOINT [ "dotnet", "regGRPC.dll" ]
