FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as builder
WORKDIR /src

COPY . .

RUN dotnet restore

RUN dotnet publish -c Release -o /published src/regGRPC/regGRPC.csproj

# Runtime image creation
FROM mcr.microsoft.com/dotnet/core/aspnet:3.0

# Uncomment the line below if running with HTTPS
# ENV ASPNETCORE_URLS=https://+:443

WORKDIR /app

COPY --from=builder /published .

ENTRYPOINT [ "dotnet", "regGRPC.dll" ]
